/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserChapter = IDL.Record({
  'subject' : IDL.Text,
  'importance' : IDL.Nat,
  'lastStudiedAt' : IDL.Opt(IDL.Int),
  'weakness' : IDL.Nat,
  'timesStudied' : IDL.Nat,
  'chapterName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'dailyStudyHours' : IDL.Float64,
  'examType' : IDL.Text,
  'examYear' : IDL.Nat,
  'examMonth' : IDL.Text,
});
export const UserStreak = IDL.Record({
  'lastActiveDate' : IDL.Text,
  'currentStreak' : IDL.Nat,
});
export const UserSubscription = IDL.Record({
  'subscriptionExpiresAt' : IDL.Opt(IDL.Int),
  'isPro' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChapters' : IDL.Func([], [IDL.Vec(UserChapter)], ['query']),
  'getDailyPlanCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMonthlyDoneCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getStreak' : IDL.Func([], [UserStreak], ['query']),
  'getSubscription' : IDL.Func([], [UserSubscription], ['query']),
  'incrementDailyPlanCount' : IDL.Func([], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markChapterDone' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Float64], [], []),
  'togglePro' : IDL.Func([], [UserSubscription], []),
  'updateWeakness' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserChapter = IDL.Record({
    'subject' : IDL.Text,
    'importance' : IDL.Nat,
    'lastStudiedAt' : IDL.Opt(IDL.Int),
    'weakness' : IDL.Nat,
    'timesStudied' : IDL.Nat,
    'chapterName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'dailyStudyHours' : IDL.Float64,
    'examType' : IDL.Text,
    'examYear' : IDL.Nat,
    'examMonth' : IDL.Text,
  });
  const UserStreak = IDL.Record({
    'lastActiveDate' : IDL.Text,
    'currentStreak' : IDL.Nat,
  });
  const UserSubscription = IDL.Record({
    'subscriptionExpiresAt' : IDL.Opt(IDL.Int),
    'isPro' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChapters' : IDL.Func([], [IDL.Vec(UserChapter)], ['query']),
    'getDailyPlanCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMonthlyDoneCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getStreak' : IDL.Func([], [UserStreak], ['query']),
    'getSubscription' : IDL.Func([], [UserSubscription], ['query']),
    'incrementDailyPlanCount' : IDL.Func([], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markChapterDone' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'togglePro' : IDL.Func([], [UserSubscription], []),
    'updateWeakness' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };