/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface UserChapter {
  'subject' : string,
  'importance' : bigint,
  'lastStudiedAt' : [] | [bigint],
  'weakness' : bigint,
  'timesStudied' : bigint,
  'chapterName' : string,
}
export interface UserProfile {
  'dailyStudyHours' : number,
  'examType' : string,
  'examYear' : bigint,
  'examMonth' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStreak {
  'lastActiveDate' : string,
  'currentStreak' : bigint,
}
export interface UserSubscription {
  'subscriptionExpiresAt' : [] | [bigint],
  'isPro' : boolean,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChapters' : ActorMethod<[], Array<UserChapter>>,
  'getDailyPlanCount' : ActorMethod<[], bigint>,
  'getMonthlyDoneCount' : ActorMethod<[], bigint>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getStreak' : ActorMethod<[], UserStreak>,
  'getSubscription' : ActorMethod<[], UserSubscription>,
  'incrementDailyPlanCount' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markChapterDone' : ActorMethod<[string], boolean>,
  'saveProfile' : ActorMethod<[string, string, bigint, number], undefined>,
  'togglePro' : ActorMethod<[], UserSubscription>,
  'updateWeakness' : ActorMethod<[string, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];